Saul 36
southworks/azure-cli pull request #22
Opened 2018-08-09 19:35 UTC by Renkon

I have implemented delete command on live output command group.

Feel free to review the code

2018-08-09 20:14 UTC, NahuelBerg requested changes
Good job!

2018-08-09 20:14 UTC, NahuelBerg commented on src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/tests/latest/test_ams_live_output_scenarios.py
> +        self.cmd('az ams live event delete -a {amsname} -g {rg} -n {liveOutputName2} --live-event-name {liveEventName}', checks=[])
There's no need to include the parameter 'checks' here as you don't have any checks to pass to the 'cmd' function, you can call 'cmd' with only the string command.

2018-08-10 17:33 UTC, damatojuan commented
@Renkon After applying the feedback from Nahuel, and resolving branch conflicts, feel free to rebase and merge

2018-08-10 19:01 UTC, NahuelBerg approved these changes

2018-08-10 19:08 UTC, damatojuan approved these changes

2018-08-10 21:37 UTC, merged