Saul 18
southworks/azure-cli pull request #33
Opened 2018-08-16 18:58 UTC by Renkon

2018-08-16 21:22 UTC, damatojuan approved these changes

2018-08-17 13:53 UTC, NahuelBerg requested changes

2018-08-17 13:53 UTC, NahuelBerg commented on src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/_help.py
> +    short-summary: Gets the Asset storage encryption keys used to decrypt content created by version 2 of the Media Services API.
It should be '**Get** the **a**sset storage..., see other commands for references.

2018-08-17 14:05 UTC, NahuelBerg approved these changes

2018-08-17 14:08 UTC, merged