Saul 42
southworks/azure-cli pull request #45
Opened 2018-08-28 19:31 UTC by Renkon

Create done 

+ extra

error handling for all

2018-08-28 22:30 UTC, damatojuan requested changes

2018-08-28 22:30 UTC, damatojuan commented on src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/_help.py
> +    short-summary: Create a new content key policy resource.
I would remove the last word 'resource' as others create commands don't have it

2018-08-28 22:30 UTC, damatojuan commented on src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/_params.py
> +                   help='Use open restriction.')
I would add something like `License or key will be delivered on every request.` to give CLI user more details about the flag.

2018-08-28 22:30 UTC, damatojuan commented on src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/_params.py
> +                   help='Use clear key configuration.')
`Use Clear Key configuration, a.k.a AES encryption. It's intended for non-DRM keys.` (taken from SDK doc & ms web docs)

2018-08-28 22:30 UTC, damatojuan commented on src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/_params.py
> +                   arg_group='Simple Policy Options',
I prefer something like `Basic Policy Options` ... anyway, we will have to double check for IR

2018-08-28 22:30 UTC, damatojuan commented on src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/operations/content_key_policy.py
> +    options = [ContentKeyPolicyOption(name='Basic policy option',
why don't parametrize the option name?

2018-08-29 14:58 UTC, damatojuan approved these changes
lgtm

2018-08-29 15:32 UTC, NahuelBerg approved these changes
Good job Ferchu

2018-08-29 15:32 UTC, merged