Saul 215
southworks/azure-cli pull request #80
Opened 2018-10-03 14:45 UTC by NahuelBerg

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

2018-10-03 16:21 UTC, damatojuan requested changes
see comments

2018-10-03 16:21 UTC, damatojuan commented on src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/operations/account_filter.py
> +    if bitrate:
if bitrate is not None

2018-10-03 16:21 UTC, damatojuan commented on src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/operations/account_filter.py
> +        raise CLIError('The transform resource was not found.')
account filter resource

2018-10-03 16:22 UTC, NahuelBerg commented on src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/operations/account_filter.py
> +        raise CLIError('The transform resource was not found.')
Copy & paste error, fixed!

2018-10-03 20:07 UTC, Renkon requested changes

2018-10-03 20:07 UTC, Renkon commented on src/command_modules/azure-cli-ams/azure/cli/command_modules/ams/operations/account_filter.py
> +    if start_timestamp is not None:
Be careful, if presentation_time_range is null, then this will explode.

2018-10-04 13:56 UTC, Renkon approved these changes
looks okish to me

2018-10-04 14:01 UTC, damatojuan approved these changes

2018-10-04 14:17 UTC, merged